[build]
  command = "npm run build"
  publish = ".next"          # SSR: the Netlify Next plugin serves this

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

